language: node_js
os: linux
dist: trusty
node_js:
  - "7"

services:
  - docker

cache:
  directories:
    - $HOME/.cache/data

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_cache:
  - mkdir -p $HOME/.cache/data

script:
  - echo -e "travis_fold:start:docker-build"
  - export REPO=$(echo ${TRAVIS_REPO_SLUG} | awk '{gsub(/\./,"_",$0);print tolower($0)}')
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - travis_wait 250 docker build -q -t $REPO:$COMMIT .
  - echo -e "travis_fold:end:docker-build"
  - echo -e "travis_fold:start:NBLAST-boot"
  - travis_wait 190 docker run --name test -p 3838:3838 -v $HOME/.cache/data:/data -v $HOME/.cache/site-library:/usr/local/lib/R/site-library --env=FASTBOOT=true $REPO:$COMMIT Rscript /loadScript.R
  - echo -e "travis_fold:end:NBLAST-boot"
  
after_success:
  - cd $TRAVIS_BUILD_DIR
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $REPO:$TAG
