#!/usr/bin/env Rscript
options(flycircuit.datadir="/home/shiny/.local/share/rpkg-flycircuit/data/")
options(rgl.useNULL=TRUE)
options(shiny.port=3838)
options(shiny.host="0.0.0.0")
if(!require("devtools")) install.packages("devtools")
if(!require("shinyURL")) install_github("aoles/shinyURL")
if(!require("git2r")) install_github("ropensci/git2r")
if(!require("Rcpp")) install.packages("Rcpp")
if(!require("shiny")) install.packages("shiny")
if(!require("ggplot2")) install.packages("ggplot2")
if(!require("downloader")) install.packages("downloader")
if(!require("rglwidget")) install.packages("rglwidget")
if(!require("shinyRGL")) install.packages("shinyRGL")
devtools::install_github("jefferis/nat", dependencies=TRUE)
devtools::source_gist("fdd1e5b6e009ff49e66be466a104fd92", filename = "install_flyconnectome_all.R")
install_github("jefferis/flycircuit", dependencies=TRUE)
install_github("jefferislab/nat.flybrains", dependencies=TRUE)
library('methods')
library(flycircuit)
allbyall=load_si_data("allbyallblastcanon_f9dc90ce5b2ffb74af37db1e3a2cb35b.desc")
dps=load_si_data("dpscanon_f9dc90ce5b2ffb74af37db1e3a2cb35b.rds")
apres16k.p0=load_si_data("apres16k.p0.rds")
