#!/usr/bin/env Rscript
options(flycircuit.datadir="/home/shiny/.local/share/rpkg-flycircuit/data/")
options(rgl.useNULL=TRUE)
options(shiny.port=3838)
options(shiny.host="0.0.0.0")
if(!require("devtools")) install.packages("devtools", dependencies=TRUE)
if(!require("jsonlite")) install.packages("jsonlite", dependencies=TRUE)
if(!require("shinyURL")) devtools::install_github("aoles/shinyURL", dependencies=TRUE)
if(!require("git2r")) devtools::install_github("ropensci/git2r", dependencies=TRUE)
if(!require("Rcpp")) install.packages("Rcpp", dependencies=TRUE)
if(!require("shiny")) install.packages("shiny", dependencies=TRUE)
if(!require("ggplot2")) install.packages("ggplot2", dependencies=TRUE)
if(!require("downloader")) install.packages("downloader", dependencies=TRUE)
if(!require("rgl")) install.packages("rgl", dependencies=TRUE)
if(!require("rglwidget")) install.packages("rglwidget", dependencies=TRUE)
if(!require("shinyRGL")) install.packages("shinyRGL", dependencies=TRUE)
library('rgl')
rgl.useNULL()
if(!require("igraph")) install.packages("igraph", dependencies=TRUE)
if(!require("rmarkdown")) install.packages("rmarkdown", dependencies=TRUE)
devtools::install_github("jefferis/nat", dependencies=TRUE)
devtools::source_gist("fdd1e5b6e009ff49e66be466a104fd92", filename = "install_flyconnectome_all.R")
devtools::install_github("jefferis/flycircuit", dependencies=TRUE)
devtools::install_github("jefferislab/nat.flybrains", dependencies=TRUE)
library('methods')
library(flycircuit)
allbyall=load_si_data("allbyallblastcanon_f9dc90ce5b2ffb74af37db1e3a2cb35b.desc")
dps=load_si_data("dpscanon_f9dc90ce5b2ffb74af37db1e3a2cb35b.rds")
apres16k.p0=load_si_data("apres16k.p0.rds")
library('nat')
nat.flybrains::download_jefferislab_registrations()
