name: Docker Image CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: docker build . --file Dockerfile --tag nblast-on-the-fly:${GITHUB_REF#refs/heads/}
    - name: Dockerize
      if: success()
      uses: manusa/actions-publish-docker@v1.1.2
      with:
        name: virtualflybrain/nblast-on-the-fly
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    
